apiVersion: apps/v1
kind: Deployment
metadata:
  name: human-api-deployment
  labels:
    app: human-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: human-api
  template:
    metadata:
      labels:
        app: human-api
    spec:
      containers:
        - name: human-api
          image: gcr.io/the-human-factor/human-api:latest
          ports:
            - containerPort: 9000
          volumeMounts:
            - name: credentials
              mountPath: "/credentials"
              readOnly: true
          env:
            - name: FLASK_ENV
              value: development
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /credentials/google-credentials.json
            - name: FLASK_DB_HOST
              value: human-api-db-postgresql.development.svc.cluster.local
            - name: FLASK_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: human-api-db-postgresql
                  key: postgresql-password

      volumes:
        - name: credentials
          secret:
            secretName: google-credentials
            items:
              - key: google-credentials.json
                path: google-credentials.json


---
apiVersion: v1
kind: Service
metadata:
  name: human-api-service
spec:
  selector:
    app: human-api
  ports:
    - port: 9000
      protocol: TCP
